### ISSUE TITLE
CI-Build for firmware

### ISSUE THREAD

**Issue by Psynosaur** [F5OEO/pluto-ori-ps#11]
Hi

Would you be in favor of me setting this up so it may build and compile automatically for us a `pluto_$TAG.frm` file?

This way we could have separate builds for different HW types.

You may only commit your change and we could get the latest build automatically.

Removing that responsibility and making it integrated.

If you're in favor, please let me know if there are any particulars to building this firmware albeit in VM or on the actual HW.

Regards
Ohan

**Comment by F5OEO** [comment]
I am working on a complete firmware building which could be done by github workflow..stay tune !

**Comment by Psynosaur** [comment]
I am on frequency
