### ISSUE TITLE
Add TDT

### ISSUE THREAD

**Issue by F5OEO** [F5OEO/pluto-ori-ps#5]
Adding TDT with the current time (ntp syncronized) could be helpfull to calculate transmission delay (second granularity)

**Comment by Psynosaur** [comment]
Could we perhaps add GPS timestamping using a Leo bodnar via USB? 

Span of FFT data + GPS timestamp.

For sharing transmission delay (second granularity) information on particular unknown RX signal, terrestrial or via QO-100.

almost like distributed Kraken sdr...

**Comment by F5OEO** [comment]
Implemented with PCR for high accuracy measurement.
